quarkus:
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    reactive:
      url: postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

  hibernate-reactive:
    database:
      generation: validate